name: UnitTests

on:
  push:
    branches:        # Run tests when commits are pushed to these branches
      - '**'
  pull_request:      # Run tests when pull requests are made on these branches
    branches:
      - master

env:
  WEBSERVER: 'none'

jobs:
  oi-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - php: '8.1'
            db: "mariadb:10.2"
          - php: '7.2'
            db: "mysql:5.7"

    name: MySql/MariaDB (${{ matrix.php }} - DB ${{ matrix.db_alias != '' && matrix.db_alias || matrix.db }})

    services:
      mysql:
        image: ${{ matrix.db }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: elkarte_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout OpenImporter
        uses: actions/checkout@v2
        with:
          repository: openimporter/openimporter
          fetch-depth: 10
          ref: ${{ env.OPENIMPORTER_BRANCH }}
          path: openimporter

      - id: database-type
        env:
          MATRIX_DB: ${{ matrix.db }}
        run: |
          db=$(echo "${MATRIX_DB%%:*}")
          echo "db=$db" >> $GITHUB_OUTPUT

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, mbstring, zip, mysqli
          coverage: xdebug
          tools: composer:v2
          ini-values: error_reporting=E_ALL, allow_url_fopen=On, opcache.enable=0

      - name: Setup Server Environment
        env:
          DB: ${{steps.database-type.outputs.db}}
          PHP_VERSION: ${{ matrix.php }}
        run: .github/setup-oi.sh $DB $PHP_VERSION
        working-directory: ./openimporter

      - name: Run Unit Tests
        env:
          DB: ${{steps.database-type.outputs.db}}
          PHP_VERSION: ${{ matrix.php }}
        run: .github/setup-results.sh $DB $PHP_VERSION
        working-directory: ./openimporter
